// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/03/2025 02:04:56
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/STAFAST/CODES/KGS/BENIN MIRROR/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/plugins/**/*.{js,ts,mjs}","D:/STAFAST/CODES/KGS/BENIN MIRROR/composables/**/*.{js,ts,mjs}","D:/STAFAST/CODES/KGS/BENIN MIRROR/utils/**/*.{js,ts,mjs}","D:/STAFAST/CODES/KGS/BENIN MIRROR/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/STAFAST/CODES/KGS/BENIN MIRROR/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;